#!/bin/bash

if [[ $EUID -eq 0 ]]; then
  chown -R :www-data .
  chmod -R g+w .
  exec su -p www-data $0
fi

composer install \
  --no-dev \
  --no-interaction \
  --no-scripts \
  --optimize-autoloader

php artisan optimize

