#!/bin/bash

echo "Current directory: $(pwd)"
echo '========== ENV =========='

env | sed -r 's|([^=]+)=(.+)|\1="\2"|' | tee .env

if [ ! -z "$APP_KEY" ]; then
  echo "APP_KEY=\"base64:$(dd if=/dev/random count=32 bs=1 | base64)\"" | tee -a .env
fi

echo '========== ENV =========='
echo

exec apache2-foreground
