#!/bin/bash


env | sed -r 's|([^=]+)=(.+)|\1="\2"|' > .env

if [ -z "$APP_KEY" ]; then
  php -r "echo 'APP_KEY=\"base64:'.base64_encode(random_bytes(32)).'\"';" >> .env
fi

chown www-data:www-data .env

echo "Current directory: $(pwd)"
echo '========== ENV =========='
echo
cat .env
echo
echo '========== ENV =========='
echo

exec apache2-foreground
