#!/bin/bash

echo "Current directory: $(pwd)"
echo '========== ENV =========='
env | sed -r 's|([^=]+)=(.+)|\1="\2"|' | tee .env
echo '========== ENV =========='
echo

if [ ! -z "$APP_KEY" ]; then
  php artisan key:generate
fi

exec apache2-foreground
