#!/bin/bash

env | sed -r 's|([^=]+)=(.+)|\1="\2"|' > .env

dir="/scripts/start.d"
for f in $(ls "$dir"); do
  source "$dir/$f"
done

chown www-data:www-data .env

echo "Current directory: $(pwd)"
echo '========== ENV =========='
echo
cat .env
echo
echo '========== ENV =========='
echo

exec apache2-foreground
